name: Feature
description: New feature request
title: "[FEATURE] "
labels:
  - enhancement

body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What needs to be built?
      placeholder: Describe the feature
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      placeholder: |
        - Requirement 1
        - Requirement 2
        - Requirement 3
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true